# Generated by Django 6.0.3 on 2026-03-19 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_project_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='color',
        ),
    ]
