# Generated by Django 6.0.3 on 2026-04-20 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
